### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TetroYT** [HmmHmmmm/BossPlugin#6]
The boss only deals damage to the players armor before dealing damage to the player, so the boss would have to destroy all the armor on a player before he starts damaging the player, even if the player is wearing only boots all the damage will go to the boots

**Comment by HmmHmmmm** [comment]
This one has to give way. PureEntitiesX develop it

I still can't edit his entity have

**Comment by TetroYT** [comment]
Can’t you just add something in your code to over right it? Cause pvping with a boss is pointless if you’re going to wear armour

**Comment by TetroYT** [comment]
could you try blocking that feature from his plugin then just for bosses because without pure entitys pvp with players wearing armor is fine

**Comment by HmmHmmmm** [comment]
I'm not sure if it is bug boss bug or PureEntitiesX. i will try check it thoroughly.

**Comment by TetroYT** [comment]
Thank you even if it isn’t your plugin thanks for putting in the effort

**Comment by TetroYT** [comment]
hey, i couldn’t find any where else to contact you so ill just do it here, do you make plugin requests?

**Comment by TetroYT** [comment]
thank you man its 100x better now i appreciate your work
